apiVersion: v1
kind: Service
metadata:
  name: {{ include "om.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "om.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9059
      targetPort: {{ .Values.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "om.selectorLabels" . | nindent 4 }}